
version: '2.1'
services:
  nexus3:
    extends:
      file: docker-compose-base.yml
      service: base-nexus3
    container_name: ${INSTANCE_NAME:-nexus3}.${INSTANCE_DOMAIN:-internal}
    hostname: ${INSTANCE_NAME:-nexus3}.${INSTANCE_DOMAIN:-internal}
    network_mode: bridge
    ports:
    - "${NEXUS3_PORT:-28081}:${NEXUS3_PORT:-28081}"
    # registry: docker-hosted@5000
    - "${NEXUS3_DOCKER_HOSTED_PORT:-5000}:5000/tcp"
    # mirror: docker-public@5001
    - "${NEXUS3_DOCKER_PUBLIC_PORT:-5001}:5001/tcp"
    # proxy: docker-central-163@5002
    #- "${NEXUS3_DOCKER_PROXY_163_PORT:-5002}:5002/tcp"
    # proxy: docker-central-hub@5003
    #- "${NEXUS3_DOCKER_PROXY_HUB_PORT:-5003}:5003/tcp"
    volumes:
    - data:/nexus-data
    #- ./data/keystore.jks:/nexus-data/keystore.jks

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
