
version: '2.1'
services:
  nexus3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - build_fileserver=https://github.com
    image: ${DOCKER_REGISTRY:-cirepo}/nexus3:3.12.0
    restart: always
    command: ["/opt/sonatype/start-nexus-repository-manager.sh"]
    container_name: ${NEXUS3_DOMAIN:-nexus3}.${INFRASTRUCTURE:-local}
    hostname: ${NEXUS3_DOMAIN:-nexus3}.${INFRASTRUCTURE:-local}
    networks:
      local-network:
        ipv4_address: 172.16.238.133
        ipv6_address: 2001:3984:3989::133
    ports:
    - "${NEXUS3_PORT:-28081}:${NEXUS3_PORT:-28081}"
    # registry: docker-hosted@5000
    - "5000:5000/tcp"
    # mirror: docker-public@5001
    - "5001:5001/tcp"
    # proxy: docker-central-163@5002
    #- "5002/tcp"
    # proxy: docker-central-hub@5003
    #- "5003/tcp"
    volumes:
    - volume-nexus3-nexus-data:/nexus-data
    #- ./keystore.jks:/nexus-data/keystore.jks
    environment:
    - DOCKER_MIRROR_GCR=${DOCKER_MIRROR_GCR:-http://gcr.io.local:5000}
    # http://nexus3.internal:28081
    #- INFRASTRUCTURE_INTERNAL_NEXUS3=${INFRASTRUCTURE_INTERNAL_NEXUS3:-}
    # http://nexus2.internal
    - INFRASTRUCTURE_INTERNAL_NEXUS2=${INFRASTRUCTURE_INTERNAL_NEXUS2:-}
    #- JKS_PASSWORD=changeit
    - NEXUS_CONTEXT=${NEXUS3_CONTEXT:-nexus}
    - NEXUS3_CONTEXT=${NEXUS3_CONTEXT:-nexus}
    - NEXUS3_DEPLOYMENT_PASSWORD=${NEXUS3_DEPLOYMENT_PASSWORD:-deployment}
    - NEXUS3_HOSTNAME=${NEXUS3_DOMAIN:-nexus3}.${INFRASTRUCTURE:-local}
    - NEXUS3_PORT=${NEXUS3_PORT:-28081}

volumes:
  volume-nexus3-nexus-data: {}

networks:
  default:
    external: true
    name: local-network

  local-network:
    external: true

#  # docker network create --driver=bridge --ipv6 --ipam-driver=default --subnet=172.16.238.0/24 --subnet=2001:3984:3989::/64 local-network
#  # docker network ls
#  # docker network inspect local-network
#  local-network:
#    external: true
#    driver: bridge
#    enable_ipv6: true
#    ipam:
#      driver: default
#      config:
#      -
#        subnet: 172.16.238.0/24
#      -
#        subnet: 2001:3984:3989::/64
