
version: '2.1'
services:
  nexus3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - build_fileserver=https://github.com
    image: ${DOCKER_REGISTRY:-home1oss}/nexus3:3.3.1
    restart: always
    command: ["bin/nexus", "run"]
    container_name: ${NEXUS3_HOSTNAME:-nexus3.local}
    hostname: ${NEXUS3_HOSTNAME:-nexus3.local}
    ports:
    - "${NEXUS3_PORT:-28081}:${NEXUS3_PORT:-28081}"
    # registry: docker-hosted@5000
    - "5000:5000/tcp"
    # mirror: docker-public@5001
    - "5001:5001/tcp"
    # proxy: docker-central-163@5002
    #- "5002/tcp"
    # proxy: docker-central-hub@5003
    #- "5003/tcp"
    volumes:
    - volume-nexus3-nexus-data:/nexus-data
    #- ./keystore.jks:/nexus-data/keystore.jks
    environment:
    # http://nexus3.internal
    - INTERNAL_NEXUS3=${INTERNAL_NEXUS3}
    # http://nexus2.internal
    #- INTERNAL_NEXUS2=${INTERNAL_NEXUS2}
    #- JKS_PASSWORD=changeit
    - NEXUS_CONTEXT=${NEXUS3_CONTEXT:-nexus}
    - NEXUS3_CONTEXT=${NEXUS3_CONTEXT:-nexus}
    - NEXUS3_DEPLOYMENT_PASSWORD=${NEXUS3_DEPLOYMENT_PASSWORD:-deployment}
    - NEXUS3_HOSTNAME=${NEXUS3_HOSTNAME:-nexus3.local}
    - NEXUS3_PORT=${NEXUS3_PORT:-28081}

networks:
  default:
    external:
      name: oss-network

volumes:
  volume-nexus3-nexus-data: {}
