
version: '2.1'
services:
  nexus3:
    build:
      context: nexus3
      dockerfile: Dockerfile
      args:
      - build_fileserver=https://github.com
    image: home1oss/nexus3:3.3.1
    restart: always
    command: ["bin/nexus", "run"]
    container_name: ${NEXUS_HOSTNAME:-nexus3.local}
    hostname: ${NEXUS_HOSTNAME:-nexus3.local}
    ports:
    - "28081:8081/tcp"
    #- "80:5000/tcp"
    #- "5002:5002/tcp"
    #- "5003:5003/tcp"
    #- "5001:5001/tcp"
    volumes:
    - nexus3-volume:/nexus-data
    #- ./keystore.jks:/nexus-data/keystore.jks
    environment:
    - INTERNAL_NEXUS=${INTERNAL_NEXUS}/content/groups/public/
    #- JKS_PASSWORD=changeit
    - NEXUS_CONTEXT=${NEXUS_CONTEXT:-nexus}
    - NEXUS_DEPLOYMENT_PASSWORD=${NEXUS_DEPLOYMENT_PASSWORD:-deployment}
    - NEXUS_HOSTNAME=${NEXUS_HOSTNAME:-nexus3.local}

  nexus3-proxy:
    build:
      context: nexus3-proxy
      dockerfile: Dockerfile
    image: home1oss/nexus3-proxy:1.10.2-alpine
    restart: always
    command: ["nginx", "-g", "daemon off;"]
    container_name: ${NEXUS_PROXY_HOSTNAME:-nexus.local}
    hostname: ${NEXUS_PROXY_HOSTNAME:-nexus.local}
    links:
    - nexus3:${FILESERVER_DOMAIN:-fileserver.local}
    - nexus3:${NEXUS_DOMAIN:-nexus3.local}
    - nexus3:${DOCKER_MIRROR_DOMAIN:-mirror.docker.local}
    - nexus3:${DOCKER_REGISTRY_DOMAIN:-registry.docker.local}
    ports:
    - "80:80/tcp"
    environment:
    - DOCKER_MIRROR_DOMAIN=${DOCKER_MIRROR_DOMAIN:-mirror.docker.local}
    - DOCKER_MIRROR_PORT=${DOCKER_MIRROR_PORT:-5001}
    - DOCKER_REGISTRY_DOMAIN=${DOCKER_REGISTRY_DOMAIN:-registry.docker.local}
    - DOCKER_REGISTRY_PORT=${DOCKER_REGISTRY_PORT:-5000}
    - FILESERVER_DOMAIN=${FILESERVER_DOMAIN:-fileserver.local}
    - NEXUS_CONTEXT=${NEXUS_CONTEXT:-nexus} #/nexus/repository/files
    - NEXUS_DEPLOYMENT_PASSWORD=${NEXUS_DEPLOYMENT_PASSWORD:-deployment}
    - NEXUS_DOMAIN=${NEXUS_DOMAIN:-nexus3.local}
    - NEXUS_PORT=${NEXUS_PORT:-8081}
    - NEXUS_PROXY_HOSTNAME=${NEXUS_PROXY_HOSTNAME:-nexus.local}

volumes:
  nexus3-volume: {}

networks:
  default:
    external:
      name: oss-network
