
version: '2.1'
services:
  nexus3-develop:
    extends:
      file: docker-compose-base.yml
      service: base-nexus3
    container_name: ${CONTAINER_HOST_NAME:-standalone.nexus3}
    environment:
    - NEXUS3_DOCKER_HOSTED_PORT=${NEXUS3_DOCKER_HOSTED_PORT:-5000}
    - NEXUS3_DOCKER_PUBLIC_PORT=${NEXUS3_DOCKER_PUBLIC_PORT:-5001}
    #- NEXUS3_DOCKER_PROXY_163_PORT=${NEXUS3_DOCKER_PROXY_163_PORT:-5002}
    #- NEXUS3_DOCKER_PROXY_HUB_PORT=${NEXUS3_DOCKER_PROXY_HUB_PORT:-5003}
    hostname: ${CONTAINER_HOST_NAME:-standalone.nexus3}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.nexus3}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/nexus3/standalone}
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.31}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::31}
    ports:
    - "${NEXUS3_PORT:-28081}:${NEXUS3_PORT:-28081}"
    # registry: docker-hosted@5000, expose through a https nginx-proxy instance
    - "${NEXUS3_DOCKER_HOSTED_PORT:-5000}/tcp"
    # mirror: docker-public@5001, expose through a https nginx-proxy instance
    - "${NEXUS3_DOCKER_PUBLIC_PORT:-5001}/tcp"
    # proxy: docker-central-163@5002, expose through a https nginx-proxy instance
    #- "${NEXUS3_DOCKER_PROXY_163_PORT:-5002}/tcp"
    # proxy: docker-central-hub@5003, expose through a https nginx-proxy instance
    #- "${NEXUS3_DOCKER_PROXY_HUB_PORT:-5003}/tcp"
    volumes:
    - data:/nexus-data
    - ${NEXUS_HOST_FILE1:-data/opt/.gitignore}:${NEXUS_CONTAINER_FILE1:-/tmp/file1}
    - ${NEXUS_HOST_FILE2:-data/opt/.gitignore}:${NEXUS_CONTAINER_FILE2:-/tmp/file2}
    #- data/keystore.jks:/nexus-data/keystore.jks

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/nexus-data
      o: bind
