
# see: https://github.com/clearent/nexus
# see: https://github.com/sonatype/docker-nexus3/blob/master/Dockerfile

# With SSL: TODO
# see: https://books.sonatype.com/nexus-book/3.0/reference/security.html#ssl-inbound
# see: http://www.eclipse.org/jetty/documentation/current/configuring-ssl.html
# keytool -keystore keystore -alias jetty -genkeypair -keyalg RSA \
# -storepass changeit -keypass changeit -keysize 2048 -validity 5000 \
# -dname "CN=*.${NEXUS_DOMAIN}, OU=Example, O=Sonatype, L=Unspecified, ST=Unspecified, C=US" \
# -ext "SAN=DNS:${NEXUS_DOMAIN},IP:${NEXUS_IP_ADDRESS}" -ext "BC=ca:true" \
#
# keytool -keystore keystore -alias jetty -genkey -keyalg RSA -sigalg SHA256withRSA -ext 'SAN=dns:jetty.eclipse.org,dns:*.jetty.org'

# npm usage:
# npm config set registry http://nexus.local:28081/nexus/repository/npm-public/
# npm config set cache ${HOME}/.npm/.cache/npm
# npm config set disturl http://nexus.local:28081/nexus/repository/npm-dist/
# npm config set sass_binary_site http://nexus.local:28081/nexus/repository/npm-sass/
# cat ~/.npmrc
# or edit '.npmrc': registry = http://localhost:8081/nexus/repository/npm-public/
# npm login --registry=http://nexus.local:28081/nexus/repository/npm-hosted/
# npm --loglevel info install -g bower
# npm publish --registry http://nexus.local:28081/nexus/repository/npm-hosted/
# or "publishConfig" : {"registry" : "http://nexus.local:28081/nexus/repository/npm-hosted/"},
# npm deprecate --registry http://nexus.local:28081/nexus/repository/npm-hosted/ testproject1@0.0.1 "This package is deprecated"

# bower usage:
# npm install -g bower && npm install -g bower-nexus3-resolver
# .bowerrc
# {
# "registry" : {
#   "search" : [ "http://nexus.local:28081/nexus/repository/bower-public" ],
#   "register" : "http://nexus.local:28081/nexus/repository/bower-hosted"
# },
# "resolvers" : [ "bower-nexus3-resolver" ],
# "nexus" : {"username" : "deployment","password" : "deployment"}
# }
# package.json "devDependencies" : {"bower-nexus3-resolver" : "*"}
# bower install jquery
# bower register example-package git://gitserver/project.git
# bower install example-package

version: '2.1'
services:
  nexus3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - build_fileserver=https://github.com
    image: ${DOCKER_REGISTRY:-registry.docker.local}/nexus3:3.2.1
    restart: always
    command: ["bin/nexus", "run"]
    container_name: ${NEXUS_HOSTNAME:-nexus3.local}
    hostname: ${NEXUS_HOSTNAME:-nexus3.local}
    ports:
    - "28081:8081/tcp"
    #- "80:5000/tcp"
    #- "5002:5002/tcp"
    #- "5003:5003/tcp"
    #- "5001:5001/tcp"
    volumes:
    - nexus3-volume:/nexus-data
    #- ./keystore.jks:/nexus-data/keystore.jks
    environment:
    - INTERNAL_NEXUS=${INTERNAL_NEXUS}/content/groups/public/
    #- JKS_PASSWORD=changeit
    - NEXUS_CONTEXT=${NEXUS_CONTEXT:-nexus}
    - NEXUS_DEPLOYMENT_PASSWORD=${NEXUS_DEPLOYMENT_PASSWORD:-deployment}
    - NEXUS_HOSTNAME=${NEXUS_HOSTNAME:-nexus3.local}

volumes:
  nexus3-volume: {}

networks:
  default:
    external:
      name: oss-network
